=== Yuzunyannn/ElementalSorcery/json_schema/tutorial_origin.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {},
    "type": "object",
    "required": [
        "title",
        "cover",
        "describe"
    ],
    "properties": {
        "title": {
            "$ref": "./common_lang.json"
        },
        "describe": {
            "$ref": "./common_lang.json"
        },
        "hover": {
            "$ref": "./common_lang.json"
        },
        "cover": {
            "$ref": "./es_item.json"
        },
        "crafts": {
            "$ref": "./es_item.json"
        },
        "building": {
            "type": "object",
            "required": [
                "structure"
            ],
            "properties": {
                "structure": {
                    "type": "string"
                },
                "custom": {
                    "type": "object",
                    "patternProperties": {
                        "^-?\\d+,-?\\d+,-?\\d+$": {
                            "$ref": "./es_item.json"
                        },
                        "^-?\\d+,-?\\d+,-?\\d+->-?\\d+,-?\\d+,-?\\d+$": {
                            "$ref": "./es_item.json"
                        }
                    },
                    "additionalProperties": false
                },
                "customBuildings": {
                    "type": "object",
                    "patternProperties": {
                        "^-?\\d+,-?\\d+,-?\\d+$": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== Yuzunyannn/ElementalSorcery/tools/tutorial/tutorials/lv4/lv4_lk8_p1_resonantIncubator.json
{
    "cover": "elementalsorcery:md_resonant_incubator",
    "title": {
        "zh_CN": "共鸣培养",
        "en_US": "Resonant Incubation"
    },
    "describe": {
        "zh_CN": "学者发现所有水晶都有一个频率属性。共鸣培养箱，通过水晶间频率的共鸣，调整生息土壤的频率，一旦频率调整到与某种水晶相同，则会在土壤中萌生出该水晶的「生命精华」。该土壤可以在水晶花园中生长出水晶花。\\n（每次水晶花成熟后，「生命精华」都会有一定几率消失)",
        "en_US": "Scholars have discovered that all crystals have a frequency attribute. Through resonance between crystals in the Resonance Incubator, the frequency of the Lived Soil is adjusted. Once the frequency matches that of a certain crystal, the 'Essence of Life' of that crystal will sprout in the soil. This soil can grow crystal flowers in the Crystal Garden.\\n(After each crystal flower matures, there is a certain chance that the 'Essence of Life' will disappear)"
    },
    "crafts": "elementalsorcery:md_resonant_incubator",
    "building": {
        "structure": "resonant_incubator",
        "custom": {
            "0,2,0": "elementalsorcery:md_resonant_incubator",
            "3,1,0": "elementalsorcery:magic_platform",
            "-3,1,0": "elementalsorcery:magic_platform",
            "0,1,3": "elementalsorcery:magic_platform",
            "0,1,-3": "elementalsorcery:magic_platform",
            "2,1,2": "elementalsorcery:magic_platform",
            "-2,1,2": "elementalsorcery:magic_platform",
            "-2,1,-2": "elementalsorcery:magic_platform",
            "2,1,-2": "elementalsorcery:magic_platform"
        }
    }
}

=== Yuzunyannn/ElementalSorcery/tools/paperwork/tutorials/lv3/lv3_lk6_p1_shockWand.json
{
    "cover": "elementalsorcery:shock_wand",
    "title": {
        "zh_CN": "冲击魔法",
        "en_US": "Shock Magic"
    },
    "describe": {
        "zh_CN": "通过魔爆权杖升级到的冲击权杖，可以借助周围的气，冲击并推动生物(无伤害)或方块，因此不会任何的消耗。\\n冲击还可以将一些不稳定的结构取出，或许这在将来会有用。\\n合成冲击权杖的部分素材可以找精灵去问问。",
        "en_US": "The Shock Wand, upgraded from the Magic Blast Wand, can utilize surrounding energy to shock and push creatures (without causing harm) or blocks, without any consumption.\\nThe shock can also extract some unstable structures, which might be useful in the future.\\nYou can ask the elves about some of the materials needed to craft the Shock Wand."
    },
    "crafts": "elementalsorcery:shock_wand"
}

=== Yuzunyannn/ElementalSorcery/tools/tutorial/tutorials/lv5/lv5_lk3_p0_fusionCrystal.json
{
    "cover": "elementalsorcery:fusion_crystal",
    "title": {
        "zh_CN": "融合水晶",
        "en_US": "Fusion Crystal"
    },
    "describe": {
        "zh_CN": "通过漩涡将许多水晶融合到一块，而形成的融合态的水晶。\\n拿在手里似乎可以稍微提升下属性。",
        "en_US": "By merging many crystals together through a vortex, a Fusion Crystal is formed. \\nHolding it seems to slightly enhance attributes."
    },
    "crafts": "elementalsorcery:fusion_crystal"
}

=== Yuzunyannn/ElementalSorcery/tools/tutorial/tutorials/lv1/lv1_lk8_p0_meltCauldron.json
{
    "cover": "elementalsorcery:melt_cauldron",
    "title": {
        "zh_CN": "熔岩锅",
        "en_US": "Melt Cauldron"
    },
    "describe": {
        "zh_CN": "熔岩锅，借助灶台，可以将原始等材料等熔炼成其他物品。\\n不过，熔岩锅只能使用一次，一旦灶台起火加入材料，在本次熔炼结束后，该锅就无法再次使用了。带熔浆冷却后，将锅打碎，取出熔炼后的物品。\\n加热温度升高，到一定温度后，需要先扔入魔石融化成溶剂，才能开始熔化其他材料\\n材料必须按照比率放，偏离比例会提升标准差。",
        "en_US": "Heating Melt Cauldron through The Hearth, raw materials can be melted into other items.\\nHowever, the Melt Cauldron can only be used once. Once the Melt Cauldron fires and materials are added, the Melt Cauldron cannot be used again after this smelting. After the Melt Cauldron is cooled, break it and items drop.\\nWhen the temperature rises to a certain, the Dimensity needs to be thrown in to melt into a solvent before add other materials.\\nMaterials must be placed according to the ratio, and deviation from the ratio will increase the standard deviation."
    },
    "crafts": [
        "elementalsorcery:melt_cauldron"
    ]
}

=== Yuzunyannn/ElementalSorcery/tools/paperwork/tutorials/lv2/lv2_lk7_p0_magiclization.json
{
    "cover": "elementalsorcery:md_magiclization",
    "title": {
        "zh_CN": "魔力化",
        "en_US": "Magiclization"
    },
    "describe": {
        "zh_CN": "在魔化箱中，元素可以被去特征化，从而得到魔力，使用能量高的元素，往往可以转化到更多的魔力。\\n在这个简陋的设备要启动转化这个过程，是需要消耗一定魔力的。\\n特别注意的，正如先人留下来的记录，一旦元素去特征化得到魔力后，再后悔也是没有用的。",
        "en_US": "In the Magiclization Box, Elements can be de-featurerized to the Magic. Using Element with high Power can often transform into more Magic.\\nTo initiate the transformation process in this device, a certain amount of Magic is required.\\n It is important to note that, as recorded by our ancestors, once the elements are de-featurerized to obtain Magic, it's useless to regret."
    },
    "crafts": "elementalsorcery:md_magiclization"
}

=== Yuzunyannn/ElementalSorcery/tools/tutorial/tutorials/lv0/lv0_lk0_p2_rite.json
{
    "cover": "elementalsorcery:rite_table",
    "title": {
        "zh_CN": "知识§k????§r",
        "en_US": "Knowledge §k????§r"
    },
    "describe": {
        "zh_CN": "通过搭建仪式，消耗祭品作为魔力启动源，将知识在§k????§r的方式，可将史蒂夫们的智慧传递下去，称这个叫映像仪式。\\n想要实现这件事，首先需要一个仪式桌。仪式桌分为不同的等级，等级越高制作越难，目前只需要制作0级的即可。除了手中的石板，仪式桌上可以放五件物品作为祭品。\\n \\n仪式进行：仪式桌放到高一格的地面上，仪式桌为中心的5×5范围不能出现任何方块，仪式桌下方为中心的5×5范围内应插满鲜花或者火把，将祭品放到桌子上，手持满耐久的木剑发动仪式。仪式成功会有天雷将知识进行同步，并以卷轴的形式给予。如果失败后，会受到天罚，仪式等级越高收到的惩罚力度越大。\\n \\n祭品选择：大多数物品都可以成为祭品，物品的好坏决定着仪式的成败。但并不是每个等级的仪式都可以使用优秀的祭品，比如钻石。等级低的仪式只能接受普通的物品，当然对于等级低的仪式来说，这已经足够了。每种祭品有「能量」属性，所有祭品的能量综合越高，仪式的成功率越大。如果高级仪式使用低级仪式的祭品，物品所能提供的能量会大打折扣。\\n0级的仪式可以石头、原木、煤炭作为祭品，显然煤炭会更好一些，另外圆石是受到众人讨厌的祭品，如果使用5个煤炭作为祭品是肯定会成功的。我把可以作为祭品的详细数据放在了§k????§r",
        "en_US": "By Rite, consuming sacrifices as a source of magical power, and through the method of §k????§r knowledge, we can connect the wisdom of the Steves. We call this the Print Rite.\\nPrepare a Ritual Table to Start. There are diff level Ritual Tables, but now creft a 0 level is all right. In addition to the slate in hand, five items can be placed on the Ritual Table as sacrifices.\\n \\nRite: Put the Ritual Table on the ground one higher, Table center range of 5 × 5 cannot have any block. Place Flowers or torches on center range of 5x5 under table. Put the sacrifice on Ritual Table and start the Rite with a wooden sword. Steve Can get knowledge on Rite success. but if fail, steve will be punished, the higher Rite level, the greater the punishment received.\\n \\nSacrifice: Most items can be sacrificed, the quality of the items determine the success or failure of Rite. But not every level of table can withstand high-end items. Low level Rite can only accept low-end items, of course for low-level Rite, this is enough. Each sacrifice has 'Power' attribute, more Power more better. If high-level Rite use low-level's sacrifice, Power will be greatly reduced.\\n0 level Rite Can use Stone, Log, Coal as sacrifice, any level Rite hate cobblestone, and 5 coal will bring success in 0 level Rit.\\nI have put the detailed data that can be used as sacrifices in §k????§r"
    },
    "crafts": [
        {
            "id": "elementalsorcery:rite_table",
            "nbt": {
                "level": 0
            }
        }
    ]
}

=== Yuzunyannn/ElementalSorcery/tools/tutorial/tutorials/lv0/lv0_lk3_p1_lantern.json
{
    "cover": "elementalsorcery:lantern",
    "title": {
        "zh_CN": "引路灯",
        "en_US": "Guide Lamp"
    },
    "describe": {
        "zh_CN": "第一个作为测试这个物品§k????§r的道具叫引路灯，它是具有魔力的一盏灯，放下后会自动发出火焰指向上一个灯。由于其的特殊性，可以通过寻求仪式获取。\\n通过shift+右键可以设置下次放置的链接位置。",
        "en_US": "The first item used to test the item §k????§r is called the Guide Lamp, which is a magical lamp can fire a flame toward the previous lamp. Steve can get it from Seek Rite.\\nShift + Right Click to set which is the previous one."
    },
    "crafts": "elementalsorcery:lantern"
}
