=== Yuzunyannn/ElementalSorcery/json_schema/tutorial_origin.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {},
    "type": "object",
    "required": [
        "title",
        "cover",
        "describe"
    ],
    "properties": {
        "title": {
            "$ref": "./common_lang.json"
        },
        "describe": {
            "$ref": "./common_lang.json"
        },
        "hover": {
            "$ref": "./common_lang.json"
        },
        "cover": {
            "$ref": "./es_item.json"
        },
        "crafts": {
            "$ref": "./es_item.json"
        },
        "building": {
            "type": "object",
            "required": [
                "structure"
            ],
            "properties": {
                "structure": {
                    "type": "string"
                },
                "custom": {
                    "type": "object",
                    "patternProperties": {
                        "^-?\\d+,-?\\d+,-?\\d+$": {
                            "$ref": "./es_item.json"
                        },
                        "^-?\\d+,-?\\d+,-?\\d+->-?\\d+,-?\\d+,-?\\d+$": {
                            "$ref": "./es_item.json"
                        }
                    },
                    "additionalProperties": false
                },
                "customBuildings": {
                    "type": "object",
                    "patternProperties": {
                        "^-?\\d+,-?\\d+,-?\\d+$": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== Yuzunyannn/ElementalSorcery/tools/tutorial/tutorials/lv5/lv5_lk1_p1_calamityGem.json
{
    "cover": "elementalsorcery:calamity_gem",
    "title": {
        "zh_CN": "灾害宝石",
        "en_US": "Calamity Gem"
    },
    "describe": {
        "zh_CN": "和精灵的交流中，召唤出了很多怪物，从这些怪物身上收集了许多的珍贵物品，似乎与某场灾害有所关联，但这并不重要。将这些物品融合到一起，制作出了一个令人恐惧的宝石，尽管它十分珍贵，但是却没有什么人想入手的东西，它会为持有者带来「灾害」。\\n「灾害」会让你打坏的方块不掉落，有限作为怪物的目标，总是被雷劈等等厄运。\\n如果你身上持有高级的「灾害」，那你已经接近死亡了。",
        "en_US": "Through communication with the elves, many monsters were summoned, and numerous precious items were collected from these monsters. It seems to be associated with a certain disaster, but that's not important. By fusing these items together, a terrifying gem was created. Despite its value, few are willing to possess it, for it brings 'Calamity' to its holder.\\n'Calamity' causes blocks you break not to drop, makes you a prime target for monsters, and subjects you to constant misfortune like being struck by lightning and more.\\nIf you carry a high level of 'Calamity,' you are nearing death."
    },
    "crafts": "elementalsorcery:calamity_gem"
}

=== Yuzunyannn/ElementalSorcery/tools/paperwork/tutorials/lv5/lv5_lk7_p0_mantraGem.json
{
    "cover": "elementalsorcery:mantra_gem",
    "title": {
        "zh_CN": "咒文有形化",
        "en_US": "Tangible Mantra"
    },
    "describe": {
        "zh_CN": "咒文写入魔典中，便可以释放，那么咒文是否可以写入物品，来制作蕴含着某些咒文能量的物品呢？学者们制作出了咒文宝石。\\n通过撰录祭坛可以将咒文写入到咒文宝石中。",
        "en_US": "Once Mantra are transcribed into the Grimoire, they can be cast. But can Mantra be transcribed into items to create items imbued with certain mantra power? Scholars have created Mantra Gem for this purpose.\\nThrough the Transcribe Altar, mantra can be written into Mantra Gem."
    },
    "crafts": "elementalsorcery:mantra_gem"
}

=== Yuzunyannn/ElementalSorcery/tools/tutorial/tutorials/lv4/lv4_lk5_p0_jumpGem.json
{
    "cover": "elementalsorcery:jump_gem",
    "title": {
        "zh_CN": "折光宝石",
        "en_US": "Refract Gem"
    },
    "describe": {
        "zh_CN": "折光宝石拥有扭曲空间的能力，是一些高级设备的材料。\\n研究可以获取到这种宝石。",
        "en_US": "The Refract Gem possesses the ability to warp space and is a material for some advanced devices.\\nResearch can yield this gem."
    },
    "crafts": [
        "elementalsorcery:jump_gem"
    ]
}

=== Yuzunyannn/ElementalSorcery/tools/paperwork/tutorials/lv5/lv5_lk15_p1_collapseWand.json
{
    "cover": "elementalsorcery:collapse_wand",
    "title": {
        "zh_CN": "塌陷权杖",
        "en_US": "Collapse Wand"
    },
    "describe": {
        "zh_CN": "将塌陷融合到魔爆权杖中，形成的塌陷权杖。可以将力量稳定有序的释放出来。表现是可以将世界中的方块直接瓦解成元素存入其中，不过瓦解效率并不是特别高。",
        "en_US": "The Collapse Wand, formed by integrating Collapse into the Magic Blast Wand, allows for the controlled release of power. It can directly disintegrate blocks in the world into elements and store them, although the disintegration efficiency is not particularly high."
    },
    "crafts": "elementalsorcery:collapse_wand"
}

=== Yuzunyannn/ElementalSorcery/tools/tutorial/tutorials/lv4/lv4_lk19_p0_supreme.json
{
    "cover": "elementalsorcery:supreme_table",
    "title": {
        "zh_CN": "天空祭坛",
        "en_US": "Sky Altar"
    },
    "describe": {
        "zh_CN": "结合众多学者的智慧制作的大型祭坛，其杰出的设计构造可以执行各种各样的功能，甚至可以取代之前的一些祭坛。\\n天空祭坛多出16格个合成空间，可以制作一些更强大的的设备；而且可以执行物质的瓦解，且几乎无损；甚至可以根据元素和结构，反向构成物质。\\n元素方桌是天空祭坛的核心，可以完成各种各样的功能，在没有祭坛的加持下，方桌仍可以作为普通的工作台进行使用，当然制作它的成本也是很高的。",
        "en_US": "Crafted with the wisdom of many scholars, the large altar boasts remarkable design and construction, capable of executing various functions, even replacing some previous altars.\\nThe Sky Altar provides an additional 16-grid crafting space, allowing for the creation of more advance devices. It can also conduct items disintegration with minimal loss and even re-construct item based on elements and structure.\\nThe Element Square Table is the core of the Sky Altar, capable of performing various functions. Even without the blessings of a altar, the table can still be used as a regular workbench, although the cost of crafting it is quite high."
    },
    "crafts": [
        "elementalsorcery:supreme_table",
        {
            "item": "elementalsorcery:supreme_table_component",
            "data": 0
        },
        {
            "item": "elementalsorcery:supreme_table_component",
            "data": 1
        }
    ],
    "building": {
        "structure": "supreme_altar",
        "custom": {
            "0,4,0": "elementalsorcery:supreme_table",
            "0,1,0": {
                "id": "elementalsorcery:magic_platform",
                "data": 1
            },
            "6,1,2": "elementalsorcery:elemental_cube",
            "6,1,-2": "elementalsorcery:elemental_cube",
            "-6,1,2": "elementalsorcery:elemental_cube",
            "-6,1,-2": "elementalsorcery:elemental_cube",
            "8,1,2": "elementalsorcery:elemental_cube",
            "8,1,-2": "elementalsorcery:elemental_cube",
            "-8,1,2": "elementalsorcery:elemental_cube",
            "-8,1,-2": "elementalsorcery:elemental_cube",
            "2,1,6": "elementalsorcery:elemental_cube",
            "-2,1,6": "elementalsorcery:elemental_cube",
            "-2,1,-6": "elementalsorcery:elemental_cube",
            "2,1,-6": "elementalsorcery:elemental_cube",
            "2,1,8": "elementalsorcery:elemental_cube",
            "-2,1,8": "elementalsorcery:elemental_cube",
            "-2,1,-8": "elementalsorcery:elemental_cube",
            "2,1,-8": "elementalsorcery:elemental_cube"
        }
    }
}

=== Yuzunyannn/ElementalSorcery/tools/paperwork/tutorials/lv4/lv4_lk0_p0_deconstructAltarTable.json
{
    "cover": "elementalsorcery:deconstruct_altar_table",
    "title": {
        "zh_CN": "瓦解小祭坛",
        "en_US": "Small Disintegration Altar"
    },
    "describe": {
        "zh_CN": "物质瓦解箱虽然可以将物质瓦解到元素，但是其只能提取物质中的一种元素，而且，转化率十分的低下。为了解决这个问题，学者们设计了物质瓦解小祭坛，来瓦解物质得到更多的元素。\\n该祭坛的使用方式和元素合成祭坛基本相同，将物质放到中心的桌子上，通过始之魔导书的瓦解咒文来启动合成。",
        "en_US": "While the Material Disintegration Box can disintegrate material into Elements, it can only extract one type of Element from the material, and moreover, the conversion rate is extremely low. To address this issue, scholars have designed the Small Material Disintegration Altar, to disintegrate material and obtain more elements.\\nThe usage of this Altar is similar to that of the Element Craft Altar. Place the material on the central table, and activate the craft with the disintegration mantra from the Spellbook of Launcher."
    },
    "crafts": "elementalsorcery:deconstruct_altar_table",
    "building": {
        "structure": "deconstruct_altar",
        "custom": {
            "0,1,0": "elementalsorcery:deconstruct_altar_table",
            "2,1,2": "elementalsorcery:elemental_cube",
            "-2,1,2": "elementalsorcery:elemental_cube",
            "-2,1,-2": "elementalsorcery:elemental_cube",
            "2,1,-2": "elementalsorcery:elemental_cube"
        }
    }
}

=== Yuzunyannn/ElementalSorcery/tools/paperwork/tutorials/lv5/lv5_lk14_p0_disintegrateStela.json
{
    "cover": "elementalsorcery:disintegrate_stela",
    "title": {
        "zh_CN": "瞬息崩解",
        "en_US": "Instant Material Collapse"
    },
    "describe": {
        "zh_CN": "无论是瓦解祭坛还是元素方桌，他们瓦解物品的速度都过于缓慢，通过元素之石和大量的末影元素构建的崩解石碑，可以快速的将物品瓦解。只要将物品右键放入其中，便可立刻被瓦解成元素存入周围的元素容器之中。\\n虽然崩解祭坛拥有极快的分解速度，甚至可以链接漏斗进行自动分解，但它依然有着一些弊端。\\n首先，它的分解产出效率介于元素方桌和瓦解祭坛之间。其次，重复分解一系列的元素会让石碑超载，元素产物的效率会大幅度下降。\\n当超载突破界限后，会发生塌陷爆炸。祝福之玉放到下方的平台上可以提供过载保护，灾害宝石则会起到反效果。",
        "en_US": "Both the Disintegration Altar and the Element Square Table have excessively slow item disintegration speeds. However, the Material Collapse Stela, constructed with Element Stone and a large amount of End Element, can quickly disintegrate items. Simply Right Clicking to place items inside it will immediately disintegrate them into elements stored in nearby element containers.\\nWhile the Collapse Altar boasts extremely fast disintegration speeds and can even be linked to funnels for automatic disintegration, it still has some drawbacks.\\nFirstly, its disintegration output efficiency falls between that of the Element Square Table and the Disintegration Altar. Secondly, repeatedly disintegrating a series of element will overload the Stela, significantly reducing the efficiency of element production.\\nWhen the overload exceeds the limit, a collapse explosion occurs. Placing a Blessing Gem on the platform below can provide overload protection, while a Calamity Gem will have the opposite effect."
    },
    "crafts": "elementalsorcery:disintegrate_stela",
    "building": {
        "structure": "disintegrate_altar",
        "custom": {
            "0,4,0": "elementalsorcery:disintegrate_stela",
            "10,1,10": "elementalsorcery:elemental_cube",
            "-10,1,10": "elementalsorcery:elemental_cube",
            "-10,1,-10": "elementalsorcery:elemental_cube",
            "10,1,-10": "elementalsorcery:elemental_cube",
            "0,1,10": "elementalsorcery:elemental_cube",
            "0,1,-10": "elementalsorcery:elemental_cube",
            "10,1,0": "elementalsorcery:elemental_cube",
            "-10,1,0": "elementalsorcery:elemental_cube"
        }
    }
}

=== Yuzunyannn/ElementalSorcery/tools/tutorial/tutorials/lv2/lv2_lk1_p0_mdHearth.json
{
    "cover": "elementalsorcery:md_hearth",
    "title": {
        "zh_CN": "魔动灶台",
        "en_US": "Magic Drive Hearth"
    },
    "describe": {
        "zh_CN": "让魔力转化成热量的装置，比普通的灶台好用的多。",
        "en_US": "A device that converts magic into heat, much more useful than the ordinary Hearth."
    },
    "crafts": "elementalsorcery:md_hearth"
}
