=== Yuzunyannn/ElementalSorcery/json_schema/tutorial_origin.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {},
    "type": "object",
    "required": [
        "title",
        "cover",
        "describe"
    ],
    "properties": {
        "title": {
            "$ref": "./common_lang.json"
        },
        "describe": {
            "$ref": "./common_lang.json"
        },
        "hover": {
            "$ref": "./common_lang.json"
        },
        "cover": {
            "$ref": "./es_item.json"
        },
        "crafts": {
            "$ref": "./es_item.json"
        },
        "building": {
            "type": "object",
            "required": [
                "structure"
            ],
            "properties": {
                "structure": {
                    "type": "string"
                },
                "custom": {
                    "type": "object",
                    "patternProperties": {
                        "^-?\\d+,-?\\d+,-?\\d+$": {
                            "$ref": "./es_item.json"
                        },
                        "^-?\\d+,-?\\d+,-?\\d+->-?\\d+,-?\\d+,-?\\d+$": {
                            "$ref": "./es_item.json"
                        }
                    },
                    "additionalProperties": false
                },
                "customBuildings": {
                    "type": "object",
                    "patternProperties": {
                        "^-?\\d+,-?\\d+,-?\\d+$": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== Yuzunyannn/ElementalSorcery/tools/paperwork/tutorials/lv4/lv4_lk12_p0_iscNormal.json
{
    "cover": "elementalsorcery:is_craft_normal",
    "title": {
        "zh_CN": "递归结构",
        "en_US": "Recursive Structure"
    },
    "describe": {
        "zh_CN": "物品的复杂程度不一样，不是所有物品都可以被直接解析的，因此「合成结构记录台」将会是你解析复杂物品的最好帮手。\\n将结构解析祭坛下方的「魔力平台换」成记录台，在记录台里用物品标定出合成的结构，便可解析出对应的内容。当然这要求着所有作为合成材料的物品能单独被结构解析台解析出来，但实际情况通常不会如你所愿。好在学者们通过在结构解析祭坛周围搭建复数的石柱来解决这个问题。只要将记录该材料的结构水晶放入石柱的箱子内，即可被结构解析台读取，从而完成结构记录。",
        "en_US": "The complexity of items varies, and not all items can be directly analyzed. Therefore, the 'Crafting Structure Recorder' will be your best helper for analyzing complex items.\\nReplace the 'Magic Platform' beneath the Structure Analysis Altar with a Crafting Structure Recorder, and use items to calibrate the synthesis structure in the Crafting Structure Recorder to analyze the corresponding content. Of course, this requires that all items used as synthesis items can be individually analyzed by the Structure Analysis Altar, but in practice, this is usually not the case. Fortunately, scholars have solved this problem by building multiple pillars around the Structure Analysis Altar. As long as the Structural Crystal recording the structure of the item is placed in the box of the pillar, it can be read by the Structure Analysis Altar, thus completing the structure recording."
    },
    "crafts": "elementalsorcery:is_craft_normal",
    "building": {
        "structure": "analysis_altar",
        "custom": {
            "0,4,0": "elementalsorcery:analysis_altar",
            "0,1,0": {
                "id": "elementalsorcery:is_craft_normal",
                "data": 1
            },
            "5,4,0": "minecraft:chest",
            "-5,4,0": "minecraft:chest",
            "0,4,5": "minecraft:chest",
            "0,4,-5": "minecraft:chest"
        },
        "customBuildings": {
            "5,0,0": "analysis_altar_add",
            "-5,0,0": "analysis_altar_add",
            "0,0,5": "analysis_altar_add",
            "0,0,-5": "analysis_altar_add"
        }
    }
}

=== Yuzunyannn/ElementalSorcery/tools/tutorial/tutorials/lv1/lv1_lk1_p0_ancientPaper.json
{
    "cover": "elementalsorcery:ancient_paper",
    "title": {
        "zh_CN": "收集文献",
        "en_US": "Collect Paper"
    },
    "describe": {
        "zh_CN": "先人似乎在封藏石种留些了许多文献，在上面记载着许多的内容，但通常是无法直接看懂的，需要进行解读。一手拿着羽毛笔，一手拿着古卷，右键点击即可开始进行解读。\\n如果解读疲倦的话，过半天之后在进行解读吧，随着解读次数的增多，越不容易疲倦。\\n如果你疲倦了，吃一点苹果糖来消除疲劳。",
        "en_US": "It seems that our ancestors left many Paper in the sealed stone, on which many things are recorded, can unscramble it to understand. With a Quill in one hand and an Ancient Paper in the other, right click to start unscramble.\\nIf you feel tried, let's unscramble after a while or eat some Apple Candy. The more unscrambling you do, the less tired you will get."
    },
    "crafts": [
        "elementalsorcery:quill",
        "elementalsorcery:apple_candy"
    ]
}

=== Yuzunyannn/ElementalSorcery/tools/paperwork/tutorials/lv2/lv2_lk4_p1_magicGoldTool.json
{
    "cover": "elementalsorcery:magic_gold_pickaxe",
    "title": {
        "zh_CN": "简易魔法工具",
        "en_US": "Simple Magic Tools"
    },
    "describe": {
        "zh_CN": "魔金可以制作工具，魔金工具的性能远超钻石工具，而且使用时由于魔力的的作用，会产生不同的效果。\\n不过可惜的是，这种工具的耐久度极低，并不适合长期使用。",
        "en_US": "Magical Gold can be used to make tools. The performance of Magical Gold tools is far better than diamond tools, and different effects will be produced when using Magical Gold tools.\\nUnfortunately, the durability of this tool is very low and it is not suitable for long-term use.",
        "ja_JP": "魔金のツールを作ることができます、魔金のツールの性能はダイヤモンドツールより超えています、 また、使用時に魔力の作用により、異なる効果が発生します。\\n残念なことに、このようなツールの耐久度はきわめて低く、長期使用には適していません。。"
    },
    "crafts": [
        "elementalsorcery:magic_gold_axe",
        "elementalsorcery:magic_gold_hoe",
        "elementalsorcery:magic_gold_pickaxe",
        "elementalsorcery:magic_gold_spade",
        "elementalsorcery:magic_gold_sword"
    ]
}

=== Yuzunyannn/ElementalSorcery/tools/paperwork/tutorials/lv1/lv1_lk3_p1_magicalEnderEye.json
{
    "cover": "elementalsorcery:magical_ender_eye",
    "title": {
        "zh_CN": "带魔力的末影之眼",
        "en_US": "Eye of Ender with Magic"
    },
    "describe": {
        "zh_CN": "通过末影之眼和魔力碎片合成，可以作为烧制使用的额外物品。\\n放在烧炼箱中，可以提升烧制速度，不过每完成一轮烧制，其耐久会降低，为0时就会消失。\\n不过没有关系，它在激活状态就会脱去魔力，变成普通的末影之眼，不过会发生小规模的爆炸，请注意。\\n此外，当其位于烧炼箱中的时候，蓝晶石工具可以被烧炼，赋予元素亲和的属性。使用带有这个属性的工具，可以让环境中的微量元素附着在其上。",
        "en_US": "Made with Eye of Ender and Magic Fragment, can as Extra item in burning.\\nPut it in Smelt Box to increase speed. However, the durability will decrease after each round of burning is completed, and it will disappear when it is 0.\\nHowever, it doesn't matter. When it is activated, it will lose its magic and become an ordinary Eye of Ender. Be careful, a small explosion will occur when active it.\\nIn addition, when it is in Smelt Box, the kyanite tools can be smelted, giving it the attribute of Element Affinity that using a tool with allows trace elements in the environment to adhere to it."
    },
    "crafts": "elementalsorcery:magical_ender_eye"
}

=== Yuzunyannn/ElementalSorcery/tools/paperwork/tutorials/lv4/lv4_lk5_p1_voidContainer.json
{
    "cover": "elementalsorcery:void_fragment",
    "title": {
        "zh_CN": "虚空容器",
        "en_US": "Void Container"
    },
    "describe": {
        "zh_CN": "「聚魂」附魔的武器在末地击杀末影生物有几率掉落虚空碎片，将魔石，虚空碎片，折光宝石，末影珍珠，以9:9:6:12的比例放入熔岩锅中，可熔炼出虚空容器。\\n虚空容器似乎有着非常规的容量，通过其和元素水晶制作的虚空元素容器，借助虚空的力量可以近乎无穷的储存一种元素，但是这种储存并不稳定，受到冲击很有可能出现元素集中泄露发生爆炸的情况，因此并不能作为元素水晶的代替。",
        "en_US": "The weapon enchanted with 'Gather Souls' has a chance to drop Void Fragment when killing End creatures in the End. By putting Dimensity, Void Fragment, Refract Gem, End Pearl into Melt Cauldron in a ratio of 9:9:6:12, you can smelt Void Container.\\nThe Void Container seems to have an unconventional capacity. By using it with Element Crystal to make Element Void Container, it can store a single element almost infinitely using the power of the void. However, this storage is unstable, and there's a high risk of elemental leakage and explosion upon impact, so it cannot replace Element Crystal."
    },
    "crafts": [
        "elementalsorcery:void_container",
        "elementalsorcery:void_container_element"
    ]
}

=== Yuzunyannn/ElementalSorcery/tools/paperwork/tutorials/lv1/lv1_lk6_p0_starBell.json
{
    "cover": {
        "id": "elementalsorcery:star_bell",
        "data": 1
    },
    "title": {
        "zh_CN": "星之铃",
        "en_US": "Star Bell"
    },
    "describe": {
        "zh_CN": "用金制作出一个铃铛，摇一摇，叮铃铃~吸引周围的动物，同时也会吸引怪物的攻击。\\手持铃铛，向星之花许愿，星之花会将星元素与铃铛共鸣，形成蓝白色的星之铃。\\n星之铃在摇动的时候，会因周围的环境发出不同特性的声音。\\n脚下有岩浆会发出清脆的声音、周围有高价值方块会发出悠长的声音、周围具有史莱姆区块会发出深沉的声音。",
        "en_US": "A bell made with Gold. Ring Ring~ Attract the surrounding animals, and also attract monster's attack.\\nHold a bell and make a wish to the Star flower. Resonating the Element of Star with bell to form a light blue Star Bell。\\nShaking the Star Bell, it will make different sounds according to the surrounding.\\nA Crisp sound when lava under your feet, a Long sound when high value Block around you, a Deep sound when you are in Slime Chunk."
    },
    "crafts": "elementalsorcery:star_bell"
}

=== Yuzunyannn/ElementalSorcery/tools/paperwork/tutorials/lv5/lv5_lk11_p0_iceRock.json
{
    "cover": "elementalsorcery:ice_rock_chip",
    "title": {
        "zh_CN": "岩冰造物",
        "en_US": "Icerock Creation"
    },
    "describe": {
        "zh_CN": "从精灵那里拿到的龙息镐，在破坏绯红水晶矿后，会掉落蓝色的碎片结晶，学者称之为「岩冰」，这些结晶碎片似乎是一种奇怪的介质，感觉并不是自然生成的。\\n学者们将其和逆变宝石熔炼到一起，得到了「岩冰晶石」，这个晶石有着非同寻常的性质，可以让稳定的元素混乱化，以一种数量与能量归一的形态存入其中，称这种形态为片元形态。这简直是一个颠覆性的发现。",
        "en_US": "After obtaining it from the elves, the Dragon Breath Pickaxe, when used to mine Scarlet Crystal Ore, drops blue crystal fragments we called 'Ice Rock'. Scholars regard these crystals as a peculiar medium, seemingly not of natural origin.\\nThey've melted them together with Invert Gem, resulting in 'Ice Rock Crystals'. These crystals possess extraordinary properties, Can confuse stable elements, allowing them to be stored in a unified form of quantity and energy, we call this unified form as 'Fragment' form. It's truly a groundbreaking discovery."
    },
    "crafts": [
        "elementalsorcery:ice_rock_spar",
        "elementalsorcery:ice_rock_crystal_block"
    ]
}

=== Yuzunyannn/ElementalSorcery/tools/tutorial/tutorials/lv1/lv1_lk3_p0_magicalEnderEye.json
{
    "cover": "elementalsorcery:magical_ender_eye",
    "title": {
        "zh_CN": "带魔力的末影之眼",
        "en_US": "Eye of Ender with Magic"
    },
    "describe": {
        "zh_CN": "通过末影之眼和魔力碎片合成，可以作为烧制使用的额外物品。\\n放在烧炼箱中，可以提升烧制速度，不过每完成一轮烧制，其耐久会降低，为0时就会消失\\n不过没有关系，它在激活状态就会脱去魔力，变成普通的末影之眼，不过会发生小规模的爆炸，请注意。\\n多个可以叠加，虽然会共同浪费耐久，不过会有意想不到的效果。",
        "en_US": "Made with Eye of Ender and Magic Fragment, can as Extra item in burning.\\nPut it in Smelt Box to increase speed. However, the durability will decrease after each round of burning is completed, and it will disappear when it is 0.\\nHowever, it doesn't matter. When it is activated, it will lose its magic and become an ordinary Eye of Ender. Be careful, a small explosion will occur when active it.\\nIt can be stacked and waste durability together, but it will have unexpected effects."
    },
    "crafts": "elementalsorcery:magical_ender_eye"
}
